name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar pruebas
        run: npm test
      - name: Ver entorno
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: echo NODE_ENV